<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.eric.fall</groupId>
        <artifactId>fall-parent</artifactId>
        <version>1.0.6</version>
        <relativePath>../fall-parent/pom.xml</relativePath>
    </parent>
    
    <artifactId>fall-boot</artifactId>
    
    <name>fall-boot</name>
    <url>http://maven.apache.org</url>
    
    
    <dependencies>
        <dependency>
            <groupId>com.eric.fall</groupId>
            <artifactId>fall-web</artifactId>
            <version>1.0.6</version>
        </dependency>
        
        <dependency>
            <groupId>com.eric.fall</groupId>
            <artifactId>fall-jdbc</artifactId>
            <version>1.0.6</version>
        </dependency>
        
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        
        
        <dependency>
        <groupId>org.apache.tomcat.embed</groupId>
        <artifactId>tomcat-embed-core</artifactId>
    </dependency>
        
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-jasper</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    
</project>
